Fix injection scope is not active error
# Problem

We occasionally observe the following error:
```
io.helidon.service.registry.ScopeNotActiveException: Injection scope io.helidon.service.registry.Service.Singleton[7] is not active.

```
# Why & What

- Making `active` `volatile` solves memory visibility. It guarantees that all threads see the most current state of the flag, preventing errors from stale, cached values.

- Moving `active = false` solves a shutdown race condition. It immediately marks the scope as inactive before its services are terminated, preventing new requests from accessing a partially dismantled scope.

In short, one change ensures the `active` state is communicated reliably, and the other ensures the state is changed at the correct time.